/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank.management.system;

import java.util.Random;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author MSSMohammad
 */
public class Account extends javax.swing.JFrame {
    
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    
    /**
     * Creates new form Account
     */
    public Account() {
        super("Create Account");
        initComponents();
        conn = dbconnect.connectDb();
        randomAcc();
        randomMICR();
        randomPin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccountPage = new javax.swing.JPanel();
        AccnumtxtAP = new javax.swing.JLabel();
        Female = new javax.swing.JRadioButton();
        AddresstxtAP = new javax.swing.JLabel();
        Male = new javax.swing.JRadioButton();
        Other = new javax.swing.JRadioButton();
        Create = new javax.swing.JButton();
        LogoAP = new javax.swing.JLabel();
        DateofbirthAP = new com.toedter.calendar.JDateChooser();
        AnswerAP = new javax.swing.JTextField();
        FullnameAP = new javax.swing.JTextField();
        ClearAP = new javax.swing.JButton();
        MnumAP = new javax.swing.JTextField();
        DateofbirthtxtAP = new javax.swing.JLabel();
        AcctypetxtAP = new javax.swing.JLabel();
        SecurityqtxtAP = new javax.swing.JLabel();
        EthnicitytxtAP = new javax.swing.JLabel();
        MobileAP = new javax.swing.JTextField();
        MobiletxtAP = new javax.swing.JLabel();
        AnswertxtAP = new javax.swing.JLabel();
        GendertxtAP = new javax.swing.JLabel();
        AddressAP = new javax.swing.JTextField();
        MnumtxtAP = new javax.swing.JLabel();
        PintxtAP = new javax.swing.JLabel();
        FullnametxtAP = new javax.swing.JLabel();
        EthnicityAP = new javax.swing.JComboBox<>();
        Back = new javax.swing.JButton();
        AcctypeAP = new javax.swing.JComboBox<>();
        AccnumAP = new javax.swing.JTextField();
        PinAP = new javax.swing.JTextField();
        NewacctxtAP = new javax.swing.JLabel();
        AmounttxtAP = new javax.swing.JLabel();
        AmountxtAP = new javax.swing.JTextField();
        SecurityqAP = new javax.swing.JComboBox<>();
        AccountPage1 = new javax.swing.JPanel();
        AccnumtxtAP1 = new javax.swing.JLabel();
        Female1 = new javax.swing.JRadioButton();
        AddresstxtAP1 = new javax.swing.JLabel();
        Male1 = new javax.swing.JRadioButton();
        Other1 = new javax.swing.JRadioButton();
        Create1 = new javax.swing.JButton();
        LogoAP1 = new javax.swing.JLabel();
        DateofbirthAP1 = new com.toedter.calendar.JDateChooser();
        AnswerAP1 = new javax.swing.JTextField();
        FullnameAP1 = new javax.swing.JTextField();
        ClearAP1 = new javax.swing.JButton();
        MnumAP1 = new javax.swing.JTextField();
        DateofbirthtxtAP1 = new javax.swing.JLabel();
        AcctypetxtAP1 = new javax.swing.JLabel();
        SecurityqtxtAP1 = new javax.swing.JLabel();
        EthnicitytxtAP1 = new javax.swing.JLabel();
        MobileAP1 = new javax.swing.JTextField();
        MobiletxtAP1 = new javax.swing.JLabel();
        AnswertxtAP1 = new javax.swing.JLabel();
        GendertxtAP1 = new javax.swing.JLabel();
        AddressAP1 = new javax.swing.JTextField();
        MnumtxtAP1 = new javax.swing.JLabel();
        PintxtAP1 = new javax.swing.JLabel();
        FullnametxtAP1 = new javax.swing.JLabel();
        EthnicityAP1 = new javax.swing.JComboBox<>();
        Back1 = new javax.swing.JButton();
        AcctypeAP1 = new javax.swing.JComboBox<>();
        AccnumAP1 = new javax.swing.JTextField();
        PinAP1 = new javax.swing.JTextField();
        NewacctxtAP1 = new javax.swing.JLabel();
        AmounttxtAP1 = new javax.swing.JLabel();
        AmountxtAP1 = new javax.swing.JTextField();
        SecurityqAP1 = new javax.swing.JComboBox<>();

        AccountPage.setBackground(new java.awt.Color(255, 255, 255));
        AccountPage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 33, 57), 3));

        AccnumtxtAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AccnumtxtAP.setText("Account Number:");

        Female.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Female.setText("Female");

        AddresstxtAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddresstxtAP.setText("Address:");

        Male.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Male.setText("Male ");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });

        Other.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Other.setText("Other");

        Create.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Create.setText("Create");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        LogoAP.setText("jLabel1");

        FullnameAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullnameAPActionPerformed(evt);
            }
        });

        ClearAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ClearAP.setText("Clear");
        ClearAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearAPActionPerformed(evt);
            }
        });

        MnumAP.setEditable(false);

        DateofbirthtxtAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DateofbirthtxtAP.setText("Date of birth:");

        AcctypetxtAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AcctypetxtAP.setText("Account type:");

        SecurityqtxtAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SecurityqtxtAP.setText("Security Question:");

        EthnicitytxtAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EthnicitytxtAP.setText("Ethnicity:");

        MobiletxtAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MobiletxtAP.setText("Mobile:");

        AnswertxtAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AnswertxtAP.setText("Answer:");

        GendertxtAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GendertxtAP.setText("Gender:");

        MnumtxtAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MnumtxtAP.setText("MICR Number:");

        PintxtAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PintxtAP.setText("PIN:");

        FullnametxtAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FullnametxtAP.setText("Name:");

        EthnicityAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EthnicityAP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "New Zealand European", "Māori", "Asian", "Pacific", "Indian/Asian", "Other" }));

        Back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        AcctypeAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AcctypeAP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Checking", "Savings", " ", " " }));

        AccnumAP.setEditable(false);
        AccnumAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccnumAPActionPerformed(evt);
            }
        });

        PinAP.setEditable(false);
        PinAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinAPActionPerformed(evt);
            }
        });

        NewacctxtAP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NewacctxtAP.setForeground(new java.awt.Color(25, 36, 70));
        NewacctxtAP.setText("New Account Registration");

        AmounttxtAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AmounttxtAP.setText("Amount:");

        SecurityqAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SecurityqAP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is the name of your first pet?", "What is the name of your mother?", "What is the name of your favouite teacher?", "What is your nickname?" }));

        javax.swing.GroupLayout AccountPageLayout = new javax.swing.GroupLayout(AccountPage);
        AccountPage.setLayout(AccountPageLayout);
        AccountPageLayout.setHorizontalGroup(
            AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPageLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(MnumtxtAP)
                        .addComponent(AccnumtxtAP)
                        .addComponent(PintxtAP)
                        .addComponent(AcctypetxtAP)
                        .addComponent(GendertxtAP)
                        .addComponent(AddresstxtAP))
                    .addComponent(AmounttxtAP))
                .addGap(18, 18, 18)
                .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccountPageLayout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateofbirthtxtAP)
                            .addComponent(FullnametxtAP, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EthnicitytxtAP)
                            .addComponent(MobiletxtAP)
                            .addComponent(SecurityqtxtAP)
                            .addComponent(AnswertxtAP))
                        .addGap(18, 18, 18)
                        .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccountPageLayout.createSequentialGroup()
                                .addComponent(Create, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addComponent(ClearAP, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AnswerAP)
                            .addComponent(FullnameAP)
                            .addComponent(DateofbirthAP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SecurityqAP, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MobileAP)
                            .addComponent(EthnicityAP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(85, 85, 85))
                    .addGroup(AccountPageLayout.createSequentialGroup()
                        .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AccountPageLayout.createSequentialGroup()
                                .addComponent(Male)
                                .addGap(18, 18, 18)
                                .addComponent(Female)
                                .addGap(18, 18, 18)
                                .addComponent(Other))
                            .addComponent(AddressAP, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AmountxtAP, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AcctypeAP, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PinAP, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MnumAP, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AccnumAP, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(AccountPageLayout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(NewacctxtAP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AccountPageLayout.createSequentialGroup()
                .addComponent(LogoAP, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AccountPageLayout.setVerticalGroup(
            AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPageLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(LogoAP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NewacctxtAP)
                .addGap(40, 40, 40)
                .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(AccountPageLayout.createSequentialGroup()
                        .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccnumtxtAP)
                            .addComponent(AccnumAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MnumtxtAP)
                            .addComponent(MnumAP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PintxtAP)
                            .addComponent(PinAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AcctypetxtAP)
                            .addComponent(AcctypeAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GendertxtAP)
                            .addComponent(Male)
                            .addComponent(Female)
                            .addComponent(Other)))
                    .addGroup(AccountPageLayout.createSequentialGroup()
                        .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FullnametxtAP)
                            .addComponent(FullnameAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateofbirthtxtAP)
                            .addComponent(DateofbirthAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EthnicitytxtAP)
                            .addComponent(EthnicityAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MobiletxtAP)
                            .addComponent(MobileAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SecurityqtxtAP)
                            .addComponent(SecurityqAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddresstxtAP)
                    .addComponent(AddressAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnswertxtAP)
                    .addComponent(AnswerAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmounttxtAP)
                    .addComponent(AmountxtAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(Create)
                    .addComponent(ClearAP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AccountPage1.setBackground(new java.awt.Color(255, 255, 255));
        AccountPage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 33, 57), 3));

        AccnumtxtAP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AccnumtxtAP1.setText("Account Number:");

        Female1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Female1.setText("Female");

        AddresstxtAP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddresstxtAP1.setText("Address:");

        Male1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Male1.setText("Male ");
        Male1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Male1ActionPerformed(evt);
            }
        });

        Other1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Other1.setText("Other");

        Create1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Create1.setText("Create");
        Create1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create1ActionPerformed(evt);
            }
        });

        LogoAP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/banking logo (2).png"))); // NOI18N

        FullnameAP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullnameAP1ActionPerformed(evt);
            }
        });

        ClearAP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ClearAP1.setText("Clear");
        ClearAP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearAP1ActionPerformed(evt);
            }
        });

        MnumAP1.setEditable(false);

        DateofbirthtxtAP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DateofbirthtxtAP1.setText("Date of birth:");

        AcctypetxtAP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AcctypetxtAP1.setText("Account type:");

        SecurityqtxtAP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SecurityqtxtAP1.setText("Security Question:");

        EthnicitytxtAP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EthnicitytxtAP1.setText("Ethnicity:");

        MobiletxtAP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MobiletxtAP1.setText("Mobile:");

        AnswertxtAP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AnswertxtAP1.setText("Answer:");

        GendertxtAP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GendertxtAP1.setText("Gender:");

        MnumtxtAP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MnumtxtAP1.setText("MICR Number:");

        PintxtAP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PintxtAP1.setText("PIN:");

        FullnametxtAP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FullnametxtAP1.setText("Name:");

        EthnicityAP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EthnicityAP1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "SriLanka", "New Zealand European", "Māori", "Asian", "Pacific", "Indian/Asian", "Other" }));

        Back1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Back1.setText("Back");
        Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back1ActionPerformed(evt);
            }
        });

        AcctypeAP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AcctypeAP1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Checking", "Savings", " ", " " }));

        AccnumAP1.setEditable(false);
        AccnumAP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccnumAP1ActionPerformed(evt);
            }
        });

        PinAP1.setEditable(false);
        PinAP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinAP1ActionPerformed(evt);
            }
        });

        NewacctxtAP1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NewacctxtAP1.setForeground(new java.awt.Color(25, 36, 70));
        NewacctxtAP1.setText("New Account Registration");

        AmounttxtAP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AmounttxtAP1.setText("Amount:");

        SecurityqAP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SecurityqAP1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is the name of your first pet?", "What is the name of your mother?", "What is the name of your favouite teacher?", "What is your nickname?" }));

        javax.swing.GroupLayout AccountPage1Layout = new javax.swing.GroupLayout(AccountPage1);
        AccountPage1.setLayout(AccountPage1Layout);
        AccountPage1Layout.setHorizontalGroup(
            AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPage1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(MnumtxtAP1)
                        .addComponent(AccnumtxtAP1)
                        .addComponent(PintxtAP1)
                        .addComponent(AcctypetxtAP1)
                        .addComponent(GendertxtAP1)
                        .addComponent(AddresstxtAP1))
                    .addComponent(AmounttxtAP1))
                .addGap(18, 18, 18)
                .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccountPage1Layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateofbirthtxtAP1)
                            .addComponent(FullnametxtAP1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EthnicitytxtAP1)
                            .addComponent(MobiletxtAP1)
                            .addComponent(SecurityqtxtAP1)
                            .addComponent(AnswertxtAP1))
                        .addGap(18, 18, 18)
                        .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccountPage1Layout.createSequentialGroup()
                                .addComponent(Create1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ClearAP1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AnswerAP1)
                            .addComponent(FullnameAP1)
                            .addComponent(DateofbirthAP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SecurityqAP1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MobileAP1)
                            .addComponent(EthnicityAP1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(85, 85, 85))
                    .addGroup(AccountPage1Layout.createSequentialGroup()
                        .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AccountPage1Layout.createSequentialGroup()
                                .addComponent(Male1)
                                .addGap(18, 18, 18)
                                .addComponent(Female1)
                                .addGap(18, 18, 18)
                                .addComponent(Other1))
                            .addComponent(AddressAP1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Back1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AmountxtAP1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AcctypeAP1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PinAP1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MnumAP1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AccnumAP1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(AccountPage1Layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(NewacctxtAP1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AccountPage1Layout.createSequentialGroup()
                .addComponent(LogoAP1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AccountPage1Layout.setVerticalGroup(
            AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPage1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(LogoAP1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NewacctxtAP1)
                .addGap(40, 40, 40)
                .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(AccountPage1Layout.createSequentialGroup()
                        .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccnumtxtAP1)
                            .addComponent(AccnumAP1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(AccountPage1Layout.createSequentialGroup()
                                .addComponent(MnumtxtAP1)
                                .addGap(23, 23, 23))
                            .addGroup(AccountPage1Layout.createSequentialGroup()
                                .addComponent(MnumAP1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PintxtAP1)
                            .addComponent(PinAP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AcctypetxtAP1)
                            .addComponent(AcctypeAP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GendertxtAP1)
                            .addComponent(Male1)
                            .addComponent(Female1)
                            .addComponent(Other1)))
                    .addGroup(AccountPage1Layout.createSequentialGroup()
                        .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FullnametxtAP1)
                            .addComponent(FullnameAP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateofbirthtxtAP1)
                            .addComponent(DateofbirthAP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EthnicitytxtAP1)
                            .addComponent(EthnicityAP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MobiletxtAP1)
                            .addComponent(MobileAP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SecurityqtxtAP1)
                            .addComponent(SecurityqAP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddresstxtAP1)
                    .addComponent(AddressAP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnswertxtAP1)
                    .addComponent(AnswerAP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmounttxtAP1)
                    .addComponent(AmountxtAP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AccountPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back1)
                    .addComponent(Create1)
                    .addComponent(ClearAP1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccountPage1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccountPage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //generate a random account number between 1 and 10000
    public void randomAcc(){
        Random ra = new Random();
        AccnumAP.setText(""+ra.nextInt(10000+1));
    }
    //generate a random MICR number between 1 and 1000
    public void randomMICR(){
        Random ra = new Random();
        MnumAP.setText(""+ra.nextInt(1000+1));
    }
    //generate a random pin number between 1 and 1000
    public void randomPin(){
        Random ra = new Random();
        PinAP.setText(""+ra.nextInt(1000+1));
    }
    
    
    public void Bal(){
        String sql = "insert into Balances(Name,Acc,MICR_No,Balance)values (?,?,?,?)";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1,FullnameAP.getText());
            pst.setString(2,AccnumAP.getText());
            pst.setString(3,MnumAP.getText());
            pst.setString(4,AmountxtAP.getText());
            pst.execute();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleActionPerformed

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here:
        String sql = "insert into Account(Acc,Name,DOB,Pin,Acc_Type,Ethnicity,MICR_No,Gender,Mob,Address,Sec_Q,Sec_A,Balance) values(?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, AccnumAP.getText());
            pst.setString(2, FullnameAP.getText());
            pst.setString(3, ((JTextField)DateofbirthAP.getDateEditor().getUiComponent()).getText());
            pst.setString(4, PinAP.getText());
            pst.setString(5, (String) AcctypeAP.getSelectedItem());
            pst.setString(6, (String) EthnicityAP.getSelectedItem());
            pst.setString(7, MnumAP.getText());

            Male.setActionCommand("Male");
            Female.setActionCommand("Female");
            Other.setActionCommand("Other");
            pst.setString(8, buttonGroup1.getSelection().getActionCommand());
            pst.setString(9, MobileAP.getText());
            pst.setString(10, AddressAP.getText());
            pst.setString(11, (String) SecurityqAP.getSelectedItem());
            pst.setString(12, AnswerAP.getText());
            pst.setString(13, AmountxtAP.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Success! Account has been created");
            Bal();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_CreateActionPerformed

    private void FullnameAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullnameAPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FullnameAPActionPerformed

    private void ClearAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearAPActionPerformed
        // TODO add your handling code here:
        AccnumAP.setText("");
        MnumAP.setText("");
        PinAP.setText("");
        AddressAP.setText("");
        FullnameAP.setText("");
        AmountxtAP.setText("");
        MobileAP.setText("");

        AnswerAP.setText("");

    }//GEN-LAST:event_ClearAPActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Authentication ob = new Authentication();
        ob.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void AccnumAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccnumAPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccnumAPActionPerformed

    private void PinAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinAPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PinAPActionPerformed

    private void Male1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Male1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Male1ActionPerformed

    private void Create1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create1ActionPerformed
        // TODO add your handling code here:
        String sql = "insert into Account(Acc,Name,DOB,Pin,Acc_Type,Ethnicity,MICR_No,Gender,Mob,Address,Sec_Q,Sec_A,Balance) values(?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, AccnumAP.getText());
            pst.setString(2, FullnameAP.getText());
            pst.setString(3, ((JTextField)DateofbirthAP.getDateEditor().getUiComponent()).getText());
            pst.setString(4, PinAP.getText());
            pst.setString(5, (String) AcctypeAP.getSelectedItem());
            pst.setString(6, (String) EthnicityAP.getSelectedItem());
            pst.setString(7, MnumAP.getText());

            Male.setActionCommand("Male");
            Female.setActionCommand("Female");
            Other.setActionCommand("Other");
            pst.setString(8, buttonGroup1.getSelection().getActionCommand());
            pst.setString(9, MobileAP.getText());
            pst.setString(10, AddressAP.getText());
            pst.setString(11, (String) SecurityqAP.getSelectedItem());
            pst.setString(12, AnswerAP.getText());
            pst.setString(13, AmountxtAP.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Success! Account has been created");
            Bal();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_Create1ActionPerformed

    private void FullnameAP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullnameAP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FullnameAP1ActionPerformed

    private void ClearAP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearAP1ActionPerformed
        // TODO add your handling code here:
        AccnumAP.setText("");
        MnumAP.setText("");
        PinAP.setText("");
        AddressAP.setText("");
        FullnameAP.setText("");
        AmountxtAP.setText("");
        MobileAP.setText("");

        AnswerAP.setText("");

    }//GEN-LAST:event_ClearAP1ActionPerformed

    private void Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Authentication ob = new Authentication();
        ob.setVisible(true);
    }//GEN-LAST:event_Back1ActionPerformed

    private void AccnumAP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccnumAP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccnumAP1ActionPerformed

    private void PinAP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinAP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PinAP1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccnumAP;
    private javax.swing.JTextField AccnumAP1;
    private javax.swing.JLabel AccnumtxtAP;
    private javax.swing.JLabel AccnumtxtAP1;
    private javax.swing.JPanel AccountPage;
    private javax.swing.JPanel AccountPage1;
    private javax.swing.JComboBox<String> AcctypeAP;
    private javax.swing.JComboBox<String> AcctypeAP1;
    private javax.swing.JLabel AcctypetxtAP;
    private javax.swing.JLabel AcctypetxtAP1;
    private javax.swing.JTextField AddressAP;
    private javax.swing.JTextField AddressAP1;
    private javax.swing.JLabel AddresstxtAP;
    private javax.swing.JLabel AddresstxtAP1;
    private javax.swing.JLabel AmounttxtAP;
    private javax.swing.JLabel AmounttxtAP1;
    private javax.swing.JTextField AmountxtAP;
    private javax.swing.JTextField AmountxtAP1;
    private javax.swing.JTextField AnswerAP;
    private javax.swing.JTextField AnswerAP1;
    private javax.swing.JLabel AnswertxtAP;
    private javax.swing.JLabel AnswertxtAP1;
    private javax.swing.JButton Back;
    private javax.swing.JButton Back1;
    private javax.swing.JButton ClearAP;
    private javax.swing.JButton ClearAP1;
    private javax.swing.JButton Create;
    private javax.swing.JButton Create1;
    private com.toedter.calendar.JDateChooser DateofbirthAP;
    private com.toedter.calendar.JDateChooser DateofbirthAP1;
    private javax.swing.JLabel DateofbirthtxtAP;
    private javax.swing.JLabel DateofbirthtxtAP1;
    private javax.swing.JComboBox<String> EthnicityAP;
    private javax.swing.JComboBox<String> EthnicityAP1;
    private javax.swing.JLabel EthnicitytxtAP;
    private javax.swing.JLabel EthnicitytxtAP1;
    private javax.swing.JRadioButton Female;
    private javax.swing.JRadioButton Female1;
    private javax.swing.JTextField FullnameAP;
    private javax.swing.JTextField FullnameAP1;
    private javax.swing.JLabel FullnametxtAP;
    private javax.swing.JLabel FullnametxtAP1;
    private javax.swing.JLabel GendertxtAP;
    private javax.swing.JLabel GendertxtAP1;
    private javax.swing.JLabel LogoAP;
    private javax.swing.JLabel LogoAP1;
    private javax.swing.JRadioButton Male;
    private javax.swing.JRadioButton Male1;
    private javax.swing.JTextField MnumAP;
    private javax.swing.JTextField MnumAP1;
    private javax.swing.JLabel MnumtxtAP;
    private javax.swing.JLabel MnumtxtAP1;
    private javax.swing.JTextField MobileAP;
    private javax.swing.JTextField MobileAP1;
    private javax.swing.JLabel MobiletxtAP;
    private javax.swing.JLabel MobiletxtAP1;
    private javax.swing.JLabel NewacctxtAP;
    private javax.swing.JLabel NewacctxtAP1;
    private javax.swing.JRadioButton Other;
    private javax.swing.JRadioButton Other1;
    private javax.swing.JTextField PinAP;
    private javax.swing.JTextField PinAP1;
    private javax.swing.JLabel PintxtAP;
    private javax.swing.JLabel PintxtAP1;
    private javax.swing.JComboBox<String> SecurityqAP;
    private javax.swing.JComboBox<String> SecurityqAP1;
    private javax.swing.JLabel SecurityqtxtAP;
    private javax.swing.JLabel SecurityqtxtAP1;
    // End of variables declaration//GEN-END:variables

}